### ISSUE TITLE
any update for php 7?

### ISSUE THREAD

**Issue by Soneji** [misoks/shopping-list#1]
Hi there

Your app is one of the best out there amongst php shopping lists. I was wondering whether you would consider upgrading it to php 7? I can help if you like?

Many thanks
a friendly llama

**Comment by misoks** [comment]
I'm not actively maintaining it anymore, so if you're interested in making
the necessary changes, have at it!

**Comment by Soneji** [comment]
Was this written in PHP 5?

**Comment by misoks** [comment]
Yep, probably either 5.3 or 5.6.

**Comment by Soneji** [comment]
instead of rewriting this for php 7 i have dockerised it in #2 Please do try setting it up with a docker-compose up. It should function the same
